name: Deploy Spring Boot Lambda

on:
  push:
    branches:
      - main # This workflow runs on pushes to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Adjust to your Java version
          distribution: 'temurin'
          cache: 'maven' # Use 'gradle' if you use Gradle

      - name: Build with Maven
        run: mvn clean package -DskipTests
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Adjust to your AWS region

      # Add this step to debug
      - name: Verify AWS Credentials
        run: |
          aws sts get-caller-identity

      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@v0.1.7
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: SpringBootLambdaFunction
          zip_file: 'target/springboot-lambda-0.0.1-SNAPSHOT-lambda-package.zip' # Update to your JAR file path
          handler: 'com.kishore.StreamLambdaHandler::handleRequest' # Update to your handler class and method
